#
# Makefile for CS 70 Memory exercises
# 
# Note: the rules in this Makefile directly compile and
# link the executables with the C++ standard library.
# Because each program is one file (rather than many), 
# there's no need to compile and link in separate stages.
#
# We also use a phony target called "all" that builds the
# executables for all the exercises

all: good bad0 bad1 bad2 bad3 bad4 bad5 bad6 bad7 bad8

good: good.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o good  good.cpp

bad0: bad0.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad0  bad0.cpp

bad1: bad1.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad1  bad1.cpp

bad2: bad2.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad2  bad2.cpp

bad3: bad3.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad3  bad3.cpp

bad4: bad4.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad4  bad4.cpp

bad5: bad5.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad5  bad5.cpp

bad6: bad6.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad6  bad6.cpp

bad7: bad7.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad7  bad7.cpp

bad8: bad8.cpp
	clang++ -g -std=c++11 -pedantic -Wall -Wextra -o bad8  bad8.cpp

clean:
	rm -f good bad0 bad1 bad2 bad3 bad4 bad5 bad6 bad7 bad8
